### ISSUE TITLE
Possible typo in ligolw_cbc_align_total_spin

### ISSUE THREAD

**Issue by SergeiOssokine** [ligo-cbc/pycbc-pylal#39]
I am not sure that this is an actual bug, but just wanted to report it it here in case it is.
On lines 144-149 of ligolw_cbc_align_total_spin
``` python
site_location_list = [\
    ("h", lal.CachedDetectors[lal.LALDetectorIndexLHODIFF]),
    ("l", lal.CachedDetectors[lal.LALDetectorIndexLLODIFF]),
    ("g", lal.CachedDetectors[lal.LALDetectorIndexGEO600DIFF]),
    ("l", lal.CachedDetectors[lal.LALDetectorIndexTAMA300DIFF]),
("l", lal.CachedDetectors[lal.LALDetectorIndexVIRGODIFF])]
```

It looks like the last 2 items should be "t","v" and not "l", "l" to correspond to TAMA and VIRGO.

**Comment by spxiwh** [comment]
@a-r-williamson @pannarale @sfairhur Please see this from @SergeiOssokine. I would be surprised if this affects any runs as Virgo is only just coming online, but this would probably need fixing for O2 .... Maybe this is just used to populate the effective distance column though, which is generally meaningless for precessing simulations.
