### ISSUE TITLE
PyCBC's custom PyLAL breaks sbank

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc-pylal#8]
Looks like we need the inspiral_metric module of pylal for sbank:

    [tito@atlas6 ~]$ . sw_install/lalsuite.sh 
    [tito@atlas6 ~]$ . sw_install/pycbc_latest/etc/pycbc-user-env.sh 
    [tito@atlas6 ~]$ lalapps_cbc_sbank --help
    Traceback (most recent call last):
      File "/home/tito/sw_install/lalsuite/libexec/lalapps/lalapps_cbc_sbank.py", line 31, in <module>
        from pylal.inspiral_metric import compute_metric
    ImportError: No module named inspiral_metric

**Comment by duncan-brown** [comment]
I can cut releases, so I will do this.

**Comment by duncan-brown** [comment]
Tito, this should be working in the 0.9.4 release, but I haven't checked actually running sbank (other than --help). Please can you check and close this issue of it works?

**Comment by titodalcanton** [comment]
Looks like it's working.
